### ISSUE TITLE
Update Player Data Automatically

### ISSUE THREAD

**Issue by BarelyFunctionalCode** [SMaloney2017/Temple-OSRS-Plugin#1]
Hey, great plugin.

Would there be a way to add a feature to the plugin where it updates your TempleOSRS profile upon login? Something like making a GET request to `https://templeosrs.com/php/add_datapoint.php?player=USERNAME`.

That way there wouldn't be a need to manually update on templeOSRS. There seems to be a separate plugin that does [something similar](https://www.templeosrs.com/faq.php#:~:text=General-,Can%20I%20Update%20Myself%20Automatically%3F,is%20no%20official%20auto%2Dupdater.), but with this being a TempleOSRS plugin I figured it would be a good place to put it.

**Comment by SMaloney2017** [comment]
Yea, absolutely!

I originally didn't plan on implementing this since the XP-Updater plugin already exists, but I've been considering adding an option to update fetched players before returning their skilling and bossing gains to avoid the event that the player doesn't exist on Temple.

This could give me an excuse to knock out both of these ideas together.

I'll start on this tonight after work, thanks for the suggestion!

**Comment by BarelyFunctionalCode** [comment]
Yeah I noticed that in the bottom of your readme file and figured this was a similar thing. 

Looking forward to the update! Now if I could just get motivated to fix up my own plugin haha.

**Comment by BarelyFunctionalCode** [comment]
Also, the XP updater updates TempleOSRS on logout and not login, so maybe it's a better idea to do it on logout.

**Comment by SMaloney2017** [comment]
Just finished up implementing the logic to auto-update the local player on logout given an xp-threshold is met and either: 
 - `the XpUpdaterPlugin is disabled `
 - `the XpUpdaterPlugin's config option for templeosrs is disabled`
 
 Tomorrow I'll quickly run through the code and make sure everything is clean before making a pull request to the plugin-hub! Going to close this request for now, thanks again!
